module.exports = {
    firstName: 'CT1',
    lastName: 'CT2',
    mobile: 'CT3',
    primaryEmail: 'CT4',
    secondaryEmail: 'CT5',
    collegeName: 'CT6',
    address: 'CT7',
    zipcode: 'CT8',
    city: 'CT9',
    state: 'CT10',
    country: 'CT11',
    dob: 'CT12',
    landline: 'CT13',
    fax: 'CT14',
    companyName: 'CT15',
    position: 'CT16',
    industry: 'CT17',
    companyWebsite: 'CT18',
    gender: 'CT19',
    branch: 'CT20',
    passoutYear: 'CT21',
    percentage: 'CT22'
}
